export interface FeatureFlags {
  ROOM_MANAGEMENT: boolean
  GUEST_MANAGEMENT: boolean
  BOOKING_MANAGEMENT: boolean
  BILLING: boolean
  STAFF_MANAGEMENT: boolean
  ATTENDANCE_TRACKING: boolean
  EXPENSE_TRACKING: boolean
  NOTIFICATIONS: boolean
  ANALYTICS_DASHBOARD: boolean
  RAZORPAY_PAYMENTS: boolean
  WHATSAPP_NOTIFICATIONS: boolean
  AUTO_CHECKOUT: boolean
  STAFF_PORTAL: boolean
  DOCUMENT_STORAGE: boolean
  AUDIT_LOG_VIEWER: boolean
  MULTI_PROPERTY: boolean
}

export const DEFAULT_FEATURE_FLAGS: FeatureFlags = {
  ROOM_MANAGEMENT: true,
  GUEST_MANAGEMENT: true,
  BOOKING_MANAGEMENT: true,
  BILLING: true,
  STAFF_MANAGEMENT: true,
  ATTENDANCE_TRACKING: true,
  EXPENSE_TRACKING: true,
  NOTIFICATIONS: true,
  ANALYTICS_DASHBOARD: false,
  RAZORPAY_PAYMENTS: false,
  WHATSAPP_NOTIFICATIONS: false,
  AUTO_CHECKOUT: false,
  STAFF_PORTAL: false,
  DOCUMENT_STORAGE: false,
  AUDIT_LOG_VIEWER: false,
  MULTI_PROPERTY: false,
}

export const BUDGET_CLIENT_FLAGS: FeatureFlags = {
  ROOM_MANAGEMENT: true,
  GUEST_MANAGEMENT: true,
  BOOKING_MANAGEMENT: true,
  BILLING: true,
  STAFF_MANAGEMENT: true,
  ATTENDANCE_TRACKING: true,
  EXPENSE_TRACKING: false,
  NOTIFICATIONS: true,
  ANALYTICS_DASHBOARD: false,
  RAZORPAY_PAYMENTS: false,
  WHATSAPP_NOTIFICATIONS: false,
  AUTO_CHECKOUT: false,
  STAFF_PORTAL: false,
  DOCUMENT_STORAGE: false,
  AUDIT_LOG_VIEWER: false,
  MULTI_PROPERTY: false,
}

export const PREMIUM_CLIENT_FLAGS: FeatureFlags = {
  ROOM_MANAGEMENT: true,
  GUEST_MANAGEMENT: true,
  BOOKING_MANAGEMENT: true,
  BILLING: true,
  STAFF_MANAGEMENT: true,
  ATTENDANCE_TRACKING: true,
  EXPENSE_TRACKING: true,
  NOTIFICATIONS: true,
  ANALYTICS_DASHBOARD: true,
  RAZORPAY_PAYMENTS: true,
  WHATSAPP_NOTIFICATIONS: true,
  AUTO_CHECKOUT: true,
  STAFF_PORTAL: true,
  DOCUMENT_STORAGE: true,
  AUDIT_LOG_VIEWER: true,
  MULTI_PROPERTY: false,
}
